### PR TITLE
Fix: Add a minimal `conda_build_config.yaml`

### LINKED ISSUE #1: @conda-forge-admin, please rerender
Looks like the Azure pipeline isn't set up correctly...

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Close #1. Looks like without this we can't kick off Azure...

### CODE REVIEW

**Comment by leofang** [comment]
@minicely what I have done in this PR:
1. Add a minimal `recipe/conda_build_config.yaml` to only contain the CUDA 11.0 docker image and its associated keys
2. Run `conda smithy rerender` to generate the Azure CI settings and whatnot

Everything is done locally, but the 2nd step could also be done in the web UI by replying `@conda-forge-admin, please rerender` in this PR.

**Comment by leofang** [comment]
cc: @jakirkham @kkraus14 So the impact of going migrators is further than I expected. The Azure CI setup was not generated correctly because, I think, [the CUDA 11.0 migrator is still ongoing](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/cuda110.yaml), so I'm fixing it in this PR by adding a CBC file.

**Comment by leofang** [comment]
btw I do not bump the build number, because no package was generated when the feedstock is created.

**Comment by mnicely** [comment]
> btw I do not bump the build number, because no package was generated when the feedstock is created.

Are you supposed to bump build number each time you update package version?
As an example, we should bump build number with the next cuSPARSELt release?

**Comment by leofang** [comment]
> > btw I do not bump the build number, because no package was generated when the feedstock is created.
> 
> Are you supposed to bump build number each time you update package version?
> As an example, we should bump build number with the next cuSPARSELt release?

No, so if the package version itself is updated, we reset the build number to 0 (see the checklist in this PR). We bump the build number when the package recipe (ex: `recipe/meta.yaml`) is updated/fixed, because, say, we mess up pinning etc.

**Comment by leofang** [comment]
Hmmm...The url isn't correct?! Let me log in the developer program and check...

**Comment by mnicely** [comment]
> Hmmm...The url isn't correct?! Let me log in the developer program and check...

Yup. Copy-paste error. I think I fixed it

**Comment by leofang** [comment]
Will check back in ~40 mins, need to do something else.

**Review by mnicely — APPROVED** [review]
Thanks for finding all my issues :smile:

**Comment by jakirkham** [comment]
> cc: @jakirkham @kkraus14 So the impact of going migrators is further than I expected. The Azure CI setup was not generated correctly because, I think, [the CUDA 11.0 migrator is still ongoing](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/cuda110.yaml), so I'm fixing it in this PR by adding a CBC file.

Right I think the migrator would have gotten here. We just added this very recently. It takes some time for the bot to pick up on these things

**Comment by leofang** [comment]
Yeah I just realized this with #4... should have been more patient 😅

**Comment by jakirkham** [comment]
All good. It seems like there were a few things we missed in the review. Thanks for catching and fixing those 😄

**Comment by leofang** [comment]
> It seems like there were a few things we missed in the review. Thanks for catching and fixing those 😄

No worries. It's hard without a CI checking through everything.

**Pull request merged**
