### PR TITLE
Bump to v0.1.0

### PR DESCRIPTION
**Pull request by leofang**
cuSPARSELt v0.1.0 requires CUDA 11.2+. Since CUDA 11.3 has not appeared on Conda-Forge yet, we use 11.2 to build and allow 11.2+ at runtime.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
cc: @mnicely

**Comment by mnicely** [comment]
Oh @leofang you are an awesome person! :tada: 
Thanks for working on this!
In this version we added ARM and Windows 10 support.
I'm working to restructure the download page to clean it up.
Let's make sure the paths are correct after the update. I'll let you know when it's complete.

**Comment by leofang** [comment]
Yes I noticed that. I will add windows later. Conda-Forge has not supported arm so I am not going to bother with it. 😁

**Comment by mnicely** [comment]
> Conda-Forge has not supported arm so I am not going to bother with it.

What did you do about SBSA (ARM) with cuTensor. BTW, v1.3.0 is imminent.

**Comment by leofang** [comment]
> > Conda-Forge has not supported arm so I am not going to bother with it.
> 
> What did you do about SBSA (ARM) with cuTensor. 

Nothing. For cuTENSOR I also only packaged for linux64 (on x64) and Windows.

> BTW, v1.3.0 is imminent.

Sounds good. Let me know when it's out! There's https://github.com/conda-forge/cutensor-feedstock but you know how to find me 😄

**Comment by leofang** [comment]
> I'm working to restructure the download page to clean it up.
> Let's make sure the paths are correct after the update. I'll let you know when it's complete.

Oh OK Matt I see what you were saying now. Currently the Windows download is behind the Dev Program wall, so we don't have a machine-readable link yet.

**Comment by mnicely** [comment]
> Currently the Windows download is behind the Dev Program wall, so we don't have a machine-readable link yet.

Thanks for letting me know. That should not be the case, I'll get it fixed.

**Comment by mnicely** [comment]
Hey @leofang,
@kkraus14 tells me Conda-forge does support ARM. Where's the disconnect?

**Comment by leofang** [comment]
> Hey @leofang,
> @kkraus14 tells me Conda-forge does support ARM. Where's the disconnect?

Well, CPU builds just fine, yes, for example we build Open MPI for Arm. But GPU builds are blocked by many components (for a list of action items, see [here](https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=cuda#adding-support-for-a-new-cuda-version)). For example, `cudatoolkit` for SBSA is not ready yet: https://github.com/conda-forge/cudatoolkit-feedstock/pull/56. Downstream packages cannot fire up until all these components are in place.

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
